# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sifi2015.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import QWidget, QFileDialog, QMessageBox, QInputDialog, QLineEdit, QDesktopWidget, QMainWindow, \
    QLabel, QApplication, QTabBar, QTableWidgetItem, QPushButton, QStyleFactory, QVBoxLayout, QFrame, QGridLayout
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon, QPixmap, QDesktopServices, QFont
from PyQt5.QtCore import QStandardPaths

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(629, 765)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 611, 703))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(600, 700))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(52, 64))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 631))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QVBoxLayout(self.layoutWidget)
        # self.verticalLayout_3.setMargin(10)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_1 = QGroupBox(self.layoutWidget)
        self.groupBox_1.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_1.setAutoFillBackground(False)
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setObjectName(_fromUtf8("groupBox_1"))
        self.plainTextEdit_seq = QPlainTextEdit(self.groupBox_1)
        self.plainTextEdit_seq.setGeometry(QtCore.QRect(10, 30, 531, 150))
        self.plainTextEdit_seq.setInputMethodHints(QtCore.Qt.ImhNone)
        self.plainTextEdit_seq.setObjectName(_fromUtf8("plainTextEdit_seq"))
        self.layoutWidget_2 = QWidget(self.groupBox_1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 180, 531, 59))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_4 = QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_1 = QLabel(self.layoutWidget_2)
        font = QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_4.addWidget(self.label_1, 0, 0, 1, 1)
        self.line = QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 1, 1, 1, 1)
        self.pushButton_openDB = QPushButton(self.layoutWidget_2)
        self.pushButton_openDB.setMaximumSize(QtCore.QSize(150, 40))
        icon = QIcon()
        icon.addPixmap(QPixmap(_fromUtf8(":/Icons/Filesystem-folder-grey-open-icon.png")), QIcon.Normal, QIcon.Off)
        self.pushButton_openDB.setIcon(icon)
        self.pushButton_openDB.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_openDB.setObjectName(_fromUtf8("pushButton_openDB"))
        self.gridLayout_4.addWidget(self.pushButton_openDB, 0, 1, 1, 1)
        self.layoutWidget_4 = QWidget(self.groupBox_1)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 240, 531, 41))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_5 = QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_2 = QLabel(self.layoutWidget_4)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_db = QComboBox(self.layoutWidget_4)
        self.comboBox_db.setMinimumSize(QtCore.QSize(230, 0))
        self.comboBox_db.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_db.setObjectName(_fromUtf8("comboBox_db"))
        self.gridLayout_5.addWidget(self.comboBox_db, 1, 1, 1, 1)
        self.groupBox_2 = QGroupBox(self.groupBox_1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 290, 271, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayoutWidget = QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(12, 30, 241, 61))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 5, 5, 5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_miss = QComboBox(self.gridLayoutWidget)
        self.comboBox_miss.setMinimumSize(QtCore.QSize(70, 0))
        self.comboBox_miss.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBox_miss.setObjectName(_fromUtf8("comboBox_miss"))
        self.comboBox_miss.addItem(_fromUtf8(""))
        self.comboBox_miss.addItem(_fromUtf8(""))
        self.comboBox_miss.addItem(_fromUtf8(""))
        self.comboBox_miss.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_miss, 1, 1, 1, 1)
        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.spinBox_size = QSpinBox(self.gridLayoutWidget)
        self.spinBox_size.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_size.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_size.setMinimum(1)
        self.spinBox_size.setProperty("value", 21)
        self.spinBox_size.setObjectName(_fromUtf8("spinBox_size"))
        self.gridLayout.addWidget(self.spinBox_size, 0, 1, 1, 1)
        self.groupBox_3 = QGroupBox(self.groupBox_1)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 361, 201))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayoutWidget_2 = QWidget(self.groupBox_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(12, 30, 331, 161))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(10, 5, 5, 5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spinBox_xmer = QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_xmer.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_xmer.setMaximumSize(QtCore.QSize(70, 16777215))
        self.spinBox_xmer.setMinimum(1)
        self.spinBox_xmer.setMaximum(1000)
        self.spinBox_xmer.setProperty("value", 8)
        self.spinBox_xmer.setObjectName(_fromUtf8("spinBox_xmer"))
        self.gridLayout_2.addWidget(self.spinBox_xmer, 6, 1, 1, 1)
        self.label_5 = QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.doubleSpinBox_access = QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_access.setMinimumSize(QtCore.QSize(70, 0))
        self.doubleSpinBox_access.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_access.setMaximum(1.0)
        self.doubleSpinBox_access.setSingleStep(0.01)
        self.doubleSpinBox_access.setProperty("value", 0.1)
        self.doubleSpinBox_access.setObjectName(_fromUtf8("doubleSpinBox_access"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_access, 4, 1, 1, 1)
        self.checkBox_end = QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_end.setChecked(True)
        self.checkBox_end.setObjectName(_fromUtf8("checkBox_end"))
        self.gridLayout_2.addWidget(self.checkBox_end, 2, 0, 1, 1)
        self.checkBox_access = QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_access.setChecked(True)
        self.checkBox_access.setObjectName(_fromUtf8("checkBox_access"))
        self.gridLayout_2.addWidget(self.checkBox_access, 4, 0, 1, 1)
        self.doubleSpinBox_end = QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_end.setMinimumSize(QtCore.QSize(70, 0))
        self.doubleSpinBox_end.setMaximumSize(QtCore.QSize(70, 16777215))
        self.doubleSpinBox_end.setMaximum(100.0)
        self.doubleSpinBox_end.setSingleStep(0.01)
        self.doubleSpinBox_end.setProperty("value", 1.0)
        self.doubleSpinBox_end.setObjectName(_fromUtf8("doubleSpinBox_end"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_end, 2, 1, 1, 1)
        self.checkBox_strand = QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_strand.setChecked(True)
        self.checkBox_strand.setObjectName(_fromUtf8("checkBox_strand"))
        self.gridLayout_2.addWidget(self.checkBox_strand, 1, 0, 1, 1)
        self.checkBox_terminal = QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_terminal.setChecked(True)
        self.checkBox_terminal.setObjectName(_fromUtf8("checkBox_terminal"))
        self.gridLayout_2.addWidget(self.checkBox_terminal, 0, 0, 1, 1)
        self.pushButton_run = QPushButton(self.groupBox_1)
        self.pushButton_run.setGeometry(QtCore.QRect(350, 320, 120, 60))
        self.pushButton_run.setMinimumSize(QtCore.QSize(120, 60))
        self.pushButton_run.setMaximumSize(QtCore.QSize(120, 60))
        font = QFont()
        font.setPointSize(12)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.pushButton_default = QPushButton(self.groupBox_1)
        self.pushButton_default.setGeometry(QtCore.QRect(430, 570, 101, 31))
        font = QFont()
        font.setPointSize(8)
        self.pushButton_default.setFont(font)
        self.pushButton_default.setObjectName(_fromUtf8("pushButton_default"))
        self.verticalLayout_3.addWidget(self.groupBox_1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_7 = QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 511, 381))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayoutWidget_3 = QWidget(self.groupBox_7)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 491, 351))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.commandLinkButton_remove = QCommandLinkButton(self.gridLayoutWidget_3)
        self.commandLinkButton_remove.setMinimumSize(QtCore.QSize(0, 50))
        self.commandLinkButton_remove.setMaximumSize(QtCore.QSize(200, 50))
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(_fromUtf8(":/Images/Images/remove.png")), QIcon.Normal, QIcon.Off)
        self.commandLinkButton_remove.setIcon(icon1)
        self.commandLinkButton_remove.setIconSize(QtCore.QSize(32, 32))
        self.commandLinkButton_remove.setObjectName(_fromUtf8("commandLinkButton_remove"))
        self.gridLayout_3.addWidget(self.commandLinkButton_remove, 4, 0, 1, 1)
        self.commandLinkButton_add = QCommandLinkButton(self.gridLayoutWidget_3)
        self.commandLinkButton_add.setMinimumSize(QtCore.QSize(0, 50))
        self.commandLinkButton_add.setMaximumSize(QtCore.QSize(200, 50))
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(_fromUtf8(":/Images/Images/add.png")), QIcon.Normal, QIcon.Off)
        self.commandLinkButton_add.setIcon(icon2)
        self.commandLinkButton_add.setIconSize(QtCore.QSize(32, 32))
        self.commandLinkButton_add.setObjectName(_fromUtf8("commandLinkButton_add"))
        self.gridLayout_3.addWidget(self.commandLinkButton_add, 3, 0, 1, 1)
        self.tableWidget = QTableWidget(self.gridLayoutWidget_3)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setRowCount(0)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 24))
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuSequences = QMenu(self.menubar)
        self.menuSequences.setObjectName(_fromUtf8("menuSequences"))
        self.menuSwitch_mode = QMenu(self.menuSequences)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.menuSwitch_mode.setFont(font)
        self.menuSwitch_mode.setObjectName(_fromUtf8("menuSwitch_mode"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QAction(MainWindow)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocumentation = QAction(MainWindow)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionDocumentation.setFont(font)
        self.actionDocumentation.setObjectName(_fromUtf8("actionDocumentation"))
        self.actionConvert_Fasta_Excel = QAction(MainWindow)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionConvert_Fasta_Excel.setFont(font)
        self.actionConvert_Fasta_Excel.setObjectName(_fromUtf8("actionConvert_Fasta_Excel"))
        self.actionOff_target_prediction = QAction(MainWindow)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionOff_target_prediction.setFont(font)
        self.actionOff_target_prediction.setObjectName(_fromUtf8("actionOff_target_prediction"))
        self.actionRNAi_design_Primer3 = QAction(MainWindow)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionRNAi_design_Primer3.setFont(font)
        self.actionRNAi_design_Primer3.setObjectName(_fromUtf8("actionRNAi_design_Primer3"))
        self.actionRNAi_design = QAction(MainWindow)
        font = QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(11)
        self.actionRNAi_design.setFont(font)
        self.actionRNAi_design.setObjectName(_fromUtf8("actionRNAi_design"))
        self.actionOff_target_prediction_2 = QAction(MainWindow)
        self.actionOff_target_prediction_2.setObjectName(_fromUtf8("actionOff_target_prediction_2"))
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuAbout.addAction(self.actionAbout)
        self.menuSwitch_mode.addAction(self.actionRNAi_design)
        self.menuSwitch_mode.addAction(self.actionOff_target_prediction_2)
        self.menuSequences.addAction(self.menuSwitch_mode.menuAction())
        self.menuSequences.addSeparator()
        self.menubar.addAction(self.menuSequences.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "siFi21", None))
        self.groupBox_1.setTitle(_translate("MainWindow", "Paste target sequence or import a file", None))
        self.label_1.setText(_translate("MainWindow", "No file selected.", None))
        self.pushButton_openDB.setText(_translate("MainWindow", "Open File", None))
        self.label_2.setText(_translate("MainWindow", "Choose database", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "siRNA settings", None))
        self.label_3.setText(_translate("MainWindow", "Select siRNA size (nt)", None))
        self.comboBox_miss.setItemText(0, _translate("MainWindow", "0", None))
        self.comboBox_miss.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox_miss.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox_miss.setItemText(3, _translate("MainWindow", "3", None))
        self.label_4.setText(_translate("MainWindow", "Mismatches", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "siRNA efficiency prediction settings", None))
        self.label_5.setText(_translate("MainWindow", "   Accessibility calculation window", None))
        self.checkBox_end.setText(_translate("MainWindow", "End stability difference", None))
        self.checkBox_access.setText(_translate("MainWindow", "Target site accessibility treshold", None))
        self.checkBox_strand.setText(_translate("MainWindow", "Strand selection", None))
        self.checkBox_terminal.setText(_translate("MainWindow", "5\' Terminal nucleotide rule", None))
        self.pushButton_run.setText(_translate("MainWindow", "Start", None))
        self.pushButton_default.setText(_translate("MainWindow", "Default Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "RNAi design", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Database Managment", None))
        self.commandLinkButton_remove.setText(_translate("MainWindow", "Delete database", None))
        self.commandLinkButton_add.setText(_translate("MainWindow", "Create new database", None))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Database managment", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuSequences.setTitle(_translate("MainWindow", "Options", None))
        self.menuSwitch_mode.setTitle(_translate("MainWindow", "Switch mode", None))
        self.actionAbout.setText(_translate("MainWindow", "About si-Fi", None))
        self.actionAbout.setToolTip(_translate("MainWindow", "About", None))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation", None))
        self.actionDocumentation.setToolTip(_translate("MainWindow", "Help", None))
        self.actionConvert_Fasta_Excel.setText(_translate("MainWindow", "Convert  Fasta <-> CSV", None))
        self.actionOff_target_prediction.setText(_translate("MainWindow", "Off-target prediction", None))
        self.actionRNAi_design_Primer3.setText(_translate("MainWindow", "RNAi design (Primer3)", None))
        self.actionRNAi_design.setText(_translate("MainWindow", "RNAi design", None))
        self.actionOff_target_prediction_2.setText(_translate("MainWindow", "Off-target prediction", None))

import sifi_2015_rc
